language: node_js

node_js:
- '6'

sudo: required
dist: trusty
addons:
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable

cache:
  yarn: true

before_script:
- export DISPLAY=:99.0
- sh -e /etc/init.d/xvfb start
- sleep 3

script:
- npm run test
- npm run lint

before_deploy:
- npm run build
- cd dist

deploy:
  skip_cleanup: true
  provider: gae
  keyfile: ngbot-853199833b9e.json
  project: ngbot-164105
