language: node_js
node_js:
- '0.10'
before_install:
- openssl aes-256-cbc -K $encrypted_4a4f5866c371_key -iv $encrypted_4a4f5866c371_iv
  -in ngbot-853199833b9e.json.enc -out ngbot-853199833b9e.json -d
- npm install -g typescript@1.0
script:
- npm test
deploy:
  provider: gae
  keyfile: angular-gitter-chatbot-c31ec3ba35dd.json
  project: ngbot-853199833b9e
