language: node_js

node_js:
- '6'

sudo: required
dist: trusty
addons:
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable

before_install:
- openssl aes-256-cbc -K $encrypted_4a4f5866c371_key -iv $encrypted_4a4f5866c371_iv
  -in ngbot-853199833b9e.json.enc -out ngbot-853199833b9e.json -d

before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - npm i -g npm@^3
  - sleep 3

script:
- npm test

deploy:
  provider: gae
  keyfile: angular-gitter-chatbot-c31ec3ba35dd.json
  project: ngbot-853199833b9e
